- project:
    check:
      jobs:
        - f38-gcc-cover:
            required-projects: &projects
              - name: github/CESNET/libyang
                override-checkout: devel
              - name: github/onqtam/doctest
                override-checkout: cesnet/2021-10-08
        - f38-clang-asan-ubsan:
            required-projects: *projects
        - f38-clang-tsan:
            required-projects: *projects
        - clang-format:
            voting: false
        - f38-cpp-coverage-diff:
            voting: false
        - f38-gcc-cover-previous:
            required-projects: *projects
