- project:
    check:
      jobs:
        - f34-gcc:
            required-projects: &projects
              - name: github/CESNET/libyang
                override-checkout: devel
              - name: github/onqtam/doctest
                override-checkout: cesnet/2021-10-08
        - f37-gcc:
            required-projects: *projects
