- project:
    check:
      jobs:
        - f34-gcc-cover:
            pre-run: ci/pre.yaml
            required-projects: &projects
              - github/CESNET/libyang
              - name: github/onqtam/doctest
                override-checkout: cesnet/fix-gcc11
        - f34-clang-asan-ubsan:
            pre-run: ci/pre.yaml
            required-projects: *projects
        - f34-clang-tsan:
            pre-run: ci/pre.yaml
            required-projects: *projects
        # - f34-cpp-coverage-diff:
        #     voting: false
        - clang-format:
            voting: false
        # - f34-gcc-cover-previous:
        #     pre-run: ci/pre.yaml
        #     required-projects: *projects
